server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notes-management
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  application:
    name: NCP-BE-simcakry

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
jwt:
  secret-key: eAW+O7sUshT4+XKHOIIsZxObn+wu4OcT8FsWwaU8ldw=
  token-expiration-days: 2